 
export const endpoints = {
  Login: "user/login",
  merchantProfile: "merchant/profile",
  merchantAdminProfile: "merchant/profile",
  ordersMerchantCreate: "orders/merchant/create",
  ordersAll: "orders/all",
  ordersImportCsv: "orders/import/csv",
  SignUp: "user/register",
  VerifyOtp: "user/verify-otp",
  ResendOtp: "user/resend-otp",
  ForgetPassword:"forget_password",
  OtpVerify:"otpVerify",
  UpdatePassword:"UpdatePassword",
  changePassword:"change-password",
  getrofile:"user/profile",
  getPrivacy:"get-privacy-policy",
  getAboutUs:"get-about-us",
  getTerms:"get-terms-conditions",
  getFaq:"get-faq",
  updateProfile:"user/profile",
  add_coach_session:"add_coach_session",
  ordersImportHistory: "orders/import/history",
  vehicleCreate: "vehicle/all",
  serviceTypeAll: 'service-type/all',
  itemCategoryAll: 'item-category/all',
  PackageSize: 'parcel-type/all',
  ordersUserCreate: 'orders/user/create',
};
 