 
export const endpoints = {
  Login: "auth/login",
  SignUp: "auth/signup",
  VerifyOtp: "auth/verify-account",
  ForgetPassword: "auth/forgot-password",
  ResetPassword: "auth/reset-password",
  VerifyResetOtp: "auth/verify-reset-otp",
  ResendOtp: "auth/resend-otp",
  merchantProfile: "merchant/profile",
  merchantAdminProfile: "merchant/profile",
  ordersMerchantCreate: "orders/merchant/create",
  ordersAll: "orders/all",
  ordersImportCsv: "orders/import/csv",
  OtpVerify: "otpVerify",
  UpdatePassword: "UpdatePassword",
  changePassword: "change-password",
  getrofile: "user/profile",
  getPrivacy: "get-privacy-policy",
  getAboutUs: "get-about-us",
  getTerms: "get-terms-conditions",
  getFaq: "get-faq",
  updateProfile: "user/profile",
  add_coach_session:"add_coach_session",
  ordersImportHistory: "orders/import/history",
  vehicleCreate: "vehicle/all",
  serviceTypeAll: 'service-type/all',
  itemCategoryAll: 'item-category/all',
  PackageSize: 'parcel-type/all',
  ordersUserCreate: 'orders/user/create',
};
 