export default {
appLogo: require('./images/logo.png'),
Onboarddingbg: require('./images/Onboarddingbg.png'),
bag: require('./images/Splashbg.png'),
Loginbg: require('./images/Loginbg.png'),
Mobile: require('./images/Mobile.png'),
appLogo1: require('./images/appLogo1.png'),
phonLogoapp: require('./images/phonLogoapp.png'),
Editpen: require('./images/Editpen.png'),
app2: require('./images/app2.png'),
sp1: require('./images/sp1.png'),
eoditphots: require('./images/eoditphots.png'),
Fixed: require('./images/Fixed.png'),
view: require('./images/view.png'),
user1: require('./images/user1.png'),
IllustrationPack: require('./images/IllustrationPack.png'),
Container: require('./images/Container.png'),
lock: require('./images/lock.png'),
Analytics: require('./images/Analytics.png'),
hide: require('./images/hide.png'),
home: require('./images/home.png'),
Questions: require('./images/Questions.png'),
mess: require('./images/email.png'),
// mess: require('./images/Email.png'),
Addressx: require('./images/Addressx.png'),
search1: require('./images/search1.png'),
menus: require('./images/menus.png'),
order: require('./images/order.png'),
Profileb: require('./images/Profileb.png'),
Phone1: require('./images/Phone1.png'),
Iconreceiv: require('./images/Iconreceiv.png'),
helpPrva: require('./images/helpPrva.png'),
IconRed: require('./images/IconRed.png'),
Location: require('./images/Location.png'),
EditProfile: require('./images/EditProfile.png'),
profiel: require('./images/profiel.png'),
rightaArrow: require('./images/rightaArrow.png'),
earing: require('./images/earing.png'),
Addressicone: require('./images/Addressicone.png'),
edit1: require('./images/edit1.png'),
light: require('./images/light.png'),
Closed: require('./images/Closed.png'),
users: require('./images/users.png'),
Accuracy: require('./images/Accuracy.png'),
Next: require('./images/Next.png'),
Calblack: require('./images/Calblack.png'),
CardImage: require('./images/CardImage.png'),
Vector: require('./images/Vector.png'),
Notification: require('./images/Notification.png'),
document: require('./images/document.png'),
MessageBlack: require('./images/MessageBlack.png'),
car: require('./images/car.png'),
trck: require('./images/trck.png'),
Truck: require('./images/Truck.png'),
Dots: require('./images/Dots.png'),
arrowqdown: require('./images/arrowqdown.png'),
delite: require('./images/delite.png'),
GeriatricoLogo: require('./images/GeriatricoLogo.png'),
more_vert: require('./images/more_vert.png'),
NewTasks: require('./images/NewTasks.png'),
time: require('./images/time.png'),
ToPickUp: require('./images/ToPickUp.png'),
qolor: require('./images/qolor.png'),
Delivering: require('./images/Delivering.png'),
Completed : require('./images/Completed.png'),
group1 : require('./images/group1.png'),

black: require('./images/black.png'),
locationpin2: require('./images/locationpin2.png'),
location1: require('./images/location1.png'),
// group: require('./images/goup2.png'),
group: require('./images/group.png'),
right: require('./images/arrowRight.png'),
Arrived: require('./images/Arrived.png'),
Pin2: require('./images/Pin2.png'),
Icon: require('./images/Icon.png'),
apple: require('./images/apple.png'),
Assigned: require('./images/Assigned.png'),
Delivered: require('./images/Delivered.png'),
MohronFag: require('./images/MohronFag.png'),
prfile: require('./images/prfile.png'),
pushup: require('./images/pushup.png'),
copy: require('./images/copy.png'),
running: require('./images/running.png'),
back: require('./images/back.png'),
cycling: require('./images/cycling.png'),
arrowDown: require('./images/arrowDown.png'),
logout: require('./images/logout.png'),
Filter: require('./images/Filter.png'),
dounArroww: require('./images/dounArroww.png'),
aboutus: require('./images/aboutus.png'),
BackLeft: require('./images/BackLeft.png'),
OrderPlaced: require('./images/OrderPlaced.png'),
userLogo: require('./images/userLogo.png'),
Deliver: require('./images/Deliver.png'),
order2: require('./images/order2.png'),
eye: require('./images/eye.png'),
SUV: require('./images/SUV.png'),
Minivan: require('./images/Minivan.png'),
BoxTruck: require('./images/BoxTruck.png'),
ContactUs: require('./images/ContactUs.png'),
ChangePassword: require('./images/ChangePassword.png'),
empty: require('./images/empty.png'),




}; 